source 'https://rubygems.org'


# Use devise for athentication
gem 'devise'
# Use devise_security_extension for security questions
gem 'devise_security_extension'
# Use pundit for authorization
gem 'pundit'
# Use mysql
gem 'mysql2'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# Use phony-rails to format phone numbers
gem 'phony_rails'
# Use bootstrap for styling
gem 'bootstrap-sass', '~> 3.3.6'
# Use slim for html syntax
gem 'slim-rails'
# Use html2slim to convert existing erb files to slim
gem 'html2slim'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# User valid email to valid all email address
gem 'valid_email'
# Use autoprefixer-rail for use css use
gem 'autoprefixer-rails'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# Use chartkick to generate charts
gem 'chartkick'
#  Use kaminari for pagination
gem 'kaminari'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  # Use rspec for testing
  gem 'rspec-rails', '~> 3.5'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'guard-rspec'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'selenium-webdriver'
  gem 'spring-commands-rspec'
  gem 'rails-controller-testing'
  gem 'vcr'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'rack-mini-profiler'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'letter_opener_web'
end

group :test do
  gem 'capybara-screenshot'
  gem 'poltergeist'
  gem 'rack_session_access'
  gem 'rack-test'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
